---
title: "Fon Getirileri"
author: "Orhan Aktas"
date: '2022-11-18'
output:   
    html_document:
      df_print: !expr knitr::kable
      toc: yes
      number_sections: yes
      toc_depth: 2
---

```{r setup, include=FALSE,echo=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE,
  class.source = "bg-warning text-warning"
)
```

#### Required Libraries {.unlisted .unnumbered}

```{r libraries, message=FALSE, warning=FALSE}
library(tidyverse)
library(readxl)
library(ggridges)
```

# Introduction
data import
```{r}

returns <- read_excel("data/returns.xlsx",range = "A2:J462")

```

data tidying
```{r}
cols <- c("code","name","type","month1","month3","month6","ybd","year1","year3","year5")

returns <- returns |> set_names(cols) 

```

```{r}
returns |>mutate(stock=ifelse(type=="Hisse Senedi Şemsiye Fonu",1,0)) |> 
  ggplot(aes(x=month1,y=type,fill=stock))+
    geom_density_ridges_gradient(scale = 3, rel_min_height = 0.01)+
  theme(legend.position="none")

  
```

Hisse senedi şemsiye fonu en çok kazandıran. Peki ayrı zaman dilimleri için bakalım.
```{r}
returns_long <- returns |>
  pivot_longer(
    cols = month1:year5,
    names_to = "duration",
    values_to = "return"
  )
```

```{r}
returns_long |>  
  ggplot(aes(x=return)) +
    geom_histogram() +
    facet_grid(vars(duration), vars(type))
```

bu pek güzel durmuyor. hisse fonları ile diğerlerini ggridges ile karşılaştıralım.
```{r}
return_stock<-returns_long |> filter(type=="Hisse Senedi Şemsiye Fonu")
return_non_stock<-returns_long |> filter(type!="Hisse Senedi Şemsiye Fonu")

  ggplot(return_non_stock,aes(x=return,y=duration))+
    geom_density_ridges(scale = 1, rel_min_height = 0.01,alpha=0.1)+
    geom_density_ridges(data=return_stock,aes(x=return,y=duration),scale = 1, rel_min_height = 0.01,alpha=0.1,col="red")
```

